"""empty message

Revision ID: 009bee5580be
Revises: 28968ec5e4c1
Create Date: 2022-10-16 15:23:23.020425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009bee5580be'
down_revision = '28968ec5e4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_constraint('UQ_users_email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('UQ_users_email', 'users', ['email'])
    op.alter_column('items', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
