"""empty message

Revision ID: 28968ec5e4c1
Revises: 4c963476f9b4
Create Date: 2022-10-14 22:04:58.476269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28968ec5e4c1'
down_revision = '4c963476f9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("UQ_users_email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("UQ_users_email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
