"""empty message

Revision ID: 4ccb13535db1
Revises: 009bee5580be
Create Date: 2022-10-16 15:56:03.168287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb13535db1'
down_revision = '009bee5580be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("UQ_users_email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("UQ_users_email", 'users', type_='unique')
    op.drop_column('users', 'email')
    op.alter_column('items', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
